### ISSUE TITLE
update version code

### ISSUE THREAD

**Issue by dimpi22** [MeenalSaxena/Android-php#6]
Error in updating version code in android .
Error:(9, 0) Could not find method versionCode() for arguments [1.0]

**Comment by dimpi22** [comment]
![error code](https://user-images.githubusercontent.com/37320453/38026727-da1e5fe0-32aa-11e8-98bf-eafb08aa8c43.png)

**Comment by mayankmandloi** [comment]
the solution is you must put integers in **versionCode** and must be incremental and in versionName we can put float in it.
